config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :articles

  get 'about', to: 'pages#about'

  resources :rules

  get 'dashboard', to: 'pages#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/rule.rb
class Rule < ApplicationRecord
    has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    skip_before_action :authenticate_user!, only: %i[index]
    before_action :set_article, only: %i[ edit update destroy ]

    def new
        @article = Article.new
    end

    def create
        @article = Article.create(article_params)
        if @article.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def index
        @article = Article.new
        @articles = Article.all.order('id DESC')
    end

    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        if @article.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end
    end

    def destroy
        @article.destroy
        redirect_to root_path
    end

    private

    def article_params
        params.require(:article).permit(:body, :title, :final)
    end

    def set_article 
        @article = Article.find(params[:id])
    end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :about ]

  def home
    @articles = Article.all.order('id DESC').first(3)
  end

  def about
  end

  def dashboard
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index]
    before_action :set_rule, only: %i[ edit update destroy ]

    def new
        @rule = Rule.new
    end

    def create
        @rule = Rule.create(rule_params)
        if @rule.save
            redirect_to rules_path
        else
            render :new
        end
    end

    def edit
        @rule = Rule.find(params[:id])
    end

    def update
        @rule = Rule.find(params[:id])
        if @rule.update(rule_params)
            redirect_to rules_path
        else
            render :edit
        end
    end

    def index
        @rule = Rule.new
        @rules = Rule.all.order('id ASC')
    end

    def destroy
        @rule.destroy
        redirect_to rules_path
    end

    private

    def rule_params
        params.require(:rule).permit(:body, :photo)
    end

    def set_rule
        @rule = Rule.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/destroy.html.erb
.design {
    
}

app/views/articles/edit.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-10 col-md-8 col-lg-6 mt-5">
            <%= render 'shared/create_article' %>
        </div>
    </div>
</div>

app/views/articles/index.html.erb
<div class="container-fluid articles-container scroll">
    <p class='neon-green p-4 mb-5 text-center'>Comunicate Aqua Club</p>
    <div class="row justify-content-center py-5 mb-5 articles-index-container scroll">
        <% @articles.each do |a| %>
            <div class="col-10 col-md-7 col-lg-8 my-2 p-3 font scroll neon-green round-border article-body bck-light">
                <p id='article-id'>Comunicat: <%= a.id %> din <%= a.created_at.to_s.split(' ').first.split('-').reverse().join('-') %></p></p>
                <p class='text-center'><%= a.title %></p>
                <p class='text-justify'><%= a.body %></p>
                <p class='text-justify'><%= a.final %></p>
                <% if current_user %>
                  <div class="news-edit">
                    <%= link_to edit_article_path(a) do %>
                                        <i class="fas fa-edit"></i>
                                   <% end %>
                    
                    <%= link_to article_path(a), method: :delete do %>
                                        <i class="fas fa-trash-alt"></i>
                                   <% end %>
                    
                  </div>
                <% end %>
            </div>
        <% end %>
    </div>
    <div class="row justify-content-center article-index-new">
        <div class="col-10 col-md-8 col-lg-7">
            <% if current_user %>
                <%= render 'shared/create_article' %>
            <% end  %>
        </div>
    </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid mt-5">
    <div class="row justify-content-center">
        <div class="col-10 col-md-8 col-lg-6 mt-5">
            <%= render 'shared/create_article' %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ro'>
  <head>
    <title>Aqua Club 🏊 Bacau</title>
    <meta name="author" content="Ursache Constantin Gabriel">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="description" content="Piscinele Aqua Club din Bacau. Aqua Club este un complex cu șapte piscine situat în municipiul Bacău, str. Lunca Bistriței, nr. 1. Printre atracții se numără o piscină cu valuri și una cu tobogane pentru copii.">
    <meta name="keywords" content="aqua, club, piscina, piscine, bacau, val, valuri, sezlong, plaja, mare, apa, muzica, distractie, pool, wave, bar, terasa, fast-food, burger">
    <meta name=”robots” content=”index, follow”>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Gruppo&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/design_shape' %>
    <%= render 'shared/modal_covid' %>
    <%= render 'shared/modal_prices' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container py-5">
    <div class="row py-5">
        <div class="col py-5">
            <%= link_to 'Log out', destroy_user_session_path, class: 'blue bck-yellow p-3 round-border', method: :delete %>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<!-- <div class="container-fluid desktop position-relative blue">
  <div class="row mt-3 mt-md-2 mt-xl-0 home-master justify-content-around mx-2"> -->
    <!-- video div -->
    <!-- <div class="col-12 col-sm-11 mb-sm-5 mt-sm-4 mt-md-0 col-xl-4 video-div home-div d-flex justify-content-center align-items-center rounded-border box-shadow">
      <video id='home-video' class='rounded-border' autostart autoplay loop muted playsinline>
        <source src='<%= video_path('AquaClubClip.webm') %>' type='video/webm;codecs="vp8,vorbis"'>
        <source src='<%= video_path('AquaClub.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'>
        <source src='<%= video_path('AquaClubClip.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'> -->
        <!-- <source src='https://res.cloudinary.com/www-aquaclub-ro/video/upload/v1592901665/aqua_kiqw88.mp4'> -->
      <!-- </video> -->
      
    <!-- </div> -->
    <!-- news div -->
    <!-- <div class="col-12 col-sm-6 col-xl-4 home-div mb-md-5 bck-yellow box-shadow news-container">
      <h1 class='font text-center blue font-weight mt-4 mb-3 news-div'><i class="fas fa-newspaper mr-3"></i>News</h1>
      <div class="articles scroll bck-yellow p-0 round-border">
          <% @articles.each do |a| %>
          <div class="article font bck-blue yellow round-border my-3">
            <p class='pt-3 px-3'><%= a.body %></p>
            <hr class='bck-yellow m-0'>
            <p class='pl-3 pb-2 m-0'><%= a.created_at.to_s.split(' ').first.split('-').reverse().join('-') %></p>
            <% if current_user %>
              <div class="news-edit">
                <%= link_to 'edit', edit_article_path(a) %>
                <%= link_to 'del', article_path(a), method: :delete %>
              </div>
            <% end %>
          </div>
          <% end %>
          <%= link_to '👉articole mai vechi', articles_path, class: 'text-center font d-block text-center' %>
      </div>
    </div> -->
    
   <!-- nav div -->
    <!-- <div class="col-12 col-sm-4 col-xl-3 home-3rd-div mb-md-5 d-flex flex-column p-0">
      <div class="row home-div d-flex align-content-between justify-content-center">
        <div class='col-11 about box-shadow' data-toggle="modal" data-target="#covid-19">
          <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-virus mr-3"></i> Covid-19</p>
        </div>
        <div class="col-11 box-shadow rules">
          <%= link_to rules_path do %>
            <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-swimming-pool mr-3"></i> Regulament</p>
          <% end %>
        </div>
        <div class="col-11 font-weight box-shadow prices" data-toggle="modal" data-target="#prices">
          <p class='font text-center m-0 d-flex justify-content-center align-items-center blue'><i class="fas fa-coins mr-3"></i> Prețuri</p>
        </div>
        <div class='col-11 about box-shadow'>
          <%= link_to about_path do %>
            <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-info-circle mr-3"></i> Despre noi</p>
          <% end %>
          </div>
      </div>
      </div>
    </div>
  </div>
</div> -->

<!-- new home page -->

<div class="container-fluid home-container scroll">
  <div class="row row-1 justify-content-center flex-sm-row mx-0 mx-sm-3">
    <div class="col-12 col-sm-6 col-lg-5 d-flex flex-column justify-content-center align-items-start home-fonts-row1 neon-green">
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-hashtag ml-2 mr-3"></i>varaastafacemvaluri</p>
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-swimmer mr-3"></i>880mp luciu de apă</p>
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-umbrella-beach mr-3"></i>2800mp de plajă</p>
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-water mr-3"></i></i>piscină cu valuri</p>
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-bacon mr-3"></i></i>piscină cu tobogane</p>
      <p class='text-left home-fonts-shadow-row1 ml-0 ml-md-2 ml-lg-5'><i class="fas fa-chair mr-3"></i></i>700 de șezlonguri*</p>

    </div>
    <!-- video div -->
    <div class="col-12 col-sm-6 col-lg-7 video-container p-0 d-flex justify-content-center">
      <video id='home-video' poster="<%= image_path('aquaAnsamblu.png')%>" autostart autoplay loop muted playsinline>
        <source src='<%= video_path('AquaClubClip.webm') %>' type='video/webm;codecs="vp8,vorbis"'>
        <source src='<%= video_path('AquaClub.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'>
        <source src='<%= video_path('AquaClubClip.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'>
        <!-- <source src='https://res.cloudinary.com/www-aquaclub-ro/video/upload/v1592901665/aqua_kiqw88.mp4'> -->
      </video>
    </div>
  </div>
  <div class="row row-2 scroll my-5 mx-0 mx-sm-3 justify-content-center align-items-start neon-green text-shadow-neon-green bck-light pt-5 px-2">
    <!-- comunicate -->
    <div class="col-12 col-sm-6 col-lg-4 d-flex flex-column justify-content-center mb-5">
      <%= link_to articles_path do %>
        <p class='text-center news-title home-button'><i class="fas fa-exclamation-circle mr-2"></i>Comunicate</p>
      <% end %>
      <div class="articles scroll">
        <% @articles.each do |a| %>
          <div class="article mb-2 p-2 text-justify">
            <p class="article-title"><%= a.title %></p>
            <p><%= a.body %></p>
            <p><%= a.final %></p>
            <p><i class="fas fa-bullhorn mr-2"></i><%= a.id %> / <%= a.created_at.to_s.split(' ').first.split('-').reverse().join('-') %></p>
            <hr class="bck-neon-green">
          </div>      
        <% end %>
      </div>
      <%= link_to articles_path do %>
        <p class='pl-2 m-0 mt-2 hover home-call-to-action'><i class="far fa-hand-point-right mr-3"></i>Toate comunicatele...</p>
      <% end %>
    </div>
    <!-- covid-19 -->
    <div class="col-12 col-sm-6 col-lg-4 d-flex flex-column justify-content-center font neon-green mb-5">
        <p class='text-center news-title home-button hover' data-toggle="modal" data-target="#covid-19"><i class="fas fa-virus mr-2"></i>Covid-19</p>
        <div class="articles scroll">
          <div class="covid-19 text-justify p-2">
            <p class='p-2 m-0'>Citește regulile pe care noi le impunem tuturor clienților noștri în perioada pandemiei. Dacă ești de acord cu ele,
              ești binevenit!
            </p>
            <p class="p-2 m-0">Nimeni din echipa Aqua Club nu are pregătire medicală, nu avem virusologi și nici 
              epidemiologi în echipă. Așadar discuțiile despre existența sau nu a virusului ne depășesc.</p>
              <p class="p-2 m-0">Vă mulțumim pentru înțelegere!</p>
              <p class="p-2 m-0">*Pe perioada pandemiei Covid-19 Aqua Club reduce capacitatea maximă la cca. 350 de locuri.</p>
            </div>
        </div>
        <p class='pl-2 m-0 mt-2 hover home-call-to-action' data-toggle="modal" data-target="#covid-19"><i class="far fa-hand-point-right mr-3"></i>Regulamentul Covid-19...</p>
    </div>
    <!-- prices -->
    <div class="col-12 col-sm-6 col-lg-4 d-flex flex-column justify-content-center font neon-green mb-5">
        <p class='text-center news-title home-button hover' data-toggle="modal" data-target="#prices"><i class="fas fa-coins mr-2"></i>Prețuri</p>
        <div class="articles scroll d-flex justify-content-center">
          <div class="prices text-center d-flex flex-column justify-content-center p-2">
            <p class='home-prices-lg mt-3'>Luni - Vineri</p>
            <p class='home-prices-sm m-0'>25 lei/persoană</p>
            <p class='home-prices-sm m-0 mb-3'>20 lei/copil ( 3 - 14 ani )</p>
            <p class='home-prices-lg m-0'>Week-end & zile libere</p>
            <p class='home-prices-sm m-0'>35 lei/persoană</p>
            <p class='home-prices-sm m-0 mb-3'>25 lei/copil > ( 3 - 14 ani )</p>
            <p class='home-prices-sm'>Plata cu <i class="far fa-money-bill-alt"></i> sau <i class="fas fa-credit-card"></i></p>
          </div>
        </div>
        <p class='pl-2 m-0 mt-2 hover home-call-to-action' data-toggle="modal" data-target="#prices"><i class="far fa-hand-point-right mr-3"></i>Mai multe informații...</p>
    </div>
  </div>
</div>

app/views/pages/meniu.html.erb
<div class="container-fluid desktop position-relative blue">
    <div class="row mt-3 mt-md-2 mt-xl-0 home-master justify-content-around mx-2">
      <!-- video div -->
      <div class="col-12 col-sm-11 mb-sm-5 mt-sm-4 mt-md-0 col-xl-4 video-div home-div d-flex justify-content-center align-items-center rounded-border box-shadow">
        <video id='home-video' class='rounded-border' autostart autoplay loop muted playsinline>
          <source src='<%= video_path('AquaClubClip.webm') %>' type='video/webm;codecs="vp8,vorbis"'>
          <source src='<%= video_path('AquaClub.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'>
          <source src='<%= video_path('AquaClubClip.mp4') %>' type='video/mp4;codecs="AVC1.4D401E, MP4A.40.2"'>
          <!-- <source src='https://res.cloudinary.com/www-aquaclub-ro/video/upload/v1592901665/aqua_kiqw88.mp4'> -->
        </video>
        
      </div>
      <!-- news div -->
      <div class="col-12 col-sm-6 col-xl-4 home-div mb-md-5 bck-yellow box-shadow news-container">
        <h1 class='font text-center blue font-weight mt-4 mb-3 news-div'><i class="fas fa-newspaper mr-3"></i>News</h1>
        <div class="articles scroll bck-yellow p-0 round-border">
            <% @articles.each do |a| %>
            <div class="article font bck-blue yellow round-border my-3">
              <p class='pt-3 px-3'><%= a.body %></p>
              <hr class='bck-yellow m-0'>
              <p class='pl-3 pb-2 m-0'><%= a.created_at.to_s.split(' ').first.split('-').reverse().join('-') %></p>
              <% if current_user %>
                <div class="news-edit">
                  <%= link_to 'edit', edit_article_path(a) %>
                  <%= link_to 'del', article_path(a), method: :delete %>
                </div>
              <% end %>
            </div>
            <% end %>
            <%= link_to '👉articole mai vechi', articles_path, class: 'text-center font d-block text-center' %>
        </div>
      </div>
     <!-- nav div -->
      <div class="col-12 col-sm-4 col-xl-3 home-3rd-div mb-md-5 d-flex flex-column p-0">
        <div class="row home-div d-flex align-content-between justify-content-center">
          <div class='col-11 about box-shadow' data-toggle="modal" data-target="#covid-19">
            <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-virus mr-3"></i> Covid-19</p>
          </div>
          <div class="col-11 box-shadow rules">
            <%= link_to rules_path do %>
              <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-swimming-pool mr-3"></i> Regulament</p>
            <% end %>
          </div>
          <div class="col-11 font-weight box-shadow prices" data-toggle="modal" data-target="#prices">
            <p class='font text-center m-0 d-flex justify-content-center align-items-center blue'><i class="fas fa-coins mr-3"></i> Prețuri</p>
          </div>
          <div class='col-11 about box-shadow'>
            <%= link_to about_path do %>
              <p class='font text-center m-0 d-flex justify-content-center align-items-center blue font-weight' ><i class="fas fa-info-circle mr-3"></i> Despre noi</p>
            <% end %>
            </div>
        </div>
        </div>
      </div>
    </div>
  </div>

app/views/rules/edit.html.erb
<div class="container-fluid">
    <div class="row mt-5">
        <div class="col">
            <%= render 'shared/create_rule' %>
        </div>
    </div>
</div>

app/views/rules/index.html.erb
<!-- rules index -->
<div class="container-fluid py-3 my-5 neon-green">
    <p class='text-center mt-5 py-2 rules-page-title'>Regulament</p>
    <div class="row my-5 justify-content-around">
        <% @rules.each do |r| %>
        <div class="col-11 col-sm-8 col-md-5 my-2 mx-1 d-flex content-justify-center align-items-center rule-card round-border">
            <%= cl_image_tag r.photo.key, height: "90%" %>
            <p class='f-w-light-y m-0 pl-2'><%= r.body %> </p>
            <% if current_user %>
                <div class='rule-controls position-absolute d-flex flex-column'>
                    <%= link_to edit_rule_path(r) do %>
                        <i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to rule_path(r), method: :delete do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                </div>
            <% end %>
        </div>
        <% end %>
    </div>
    
    <% if current_user %>
        <div class="row mx-2 my-5 justify-content-center">
            <div class="col-12 col-sm-8 col-md-5 mb-5">
                <%= render 'shared/create_rule'%>
            </div>
        </div>
    <% end %>
</div>

app/views/rules/new.html.erb
<div class="container-fluid">
    <div class="row mt-5">
        <div class="col">
            <%= render 'shared/create_rule' %>
        </div>
    </div>
</div>

app/views/shared/_create_article.html.erb
<div class='neon-green create-article-font'>
    <% if @article.id %>
        <p class='text-center mt-5 create-article-font'>Modifică comunicatul</p>
    <% else %>
        <p class='text-center mt-5 create-article-font'>Creează un comunicat</p>
    <% end %>
    <%= simple_form_for @article do |f| %>
        <%= f.input :title, label: 'Titlu' %>
        <%= f.input :body, label: 'Conținut' %>
        <%= f.input :final, label: 'Final line' %>
        <% if @article.id %>
            <%= f.button :submit, value: 'Salvează', class: 'bck-light neon-square-button' %>
        <% else %>
            <%= f.button :submit, value: 'Comunicat nou', class: 'bck-light neon-square-button' %>
        <% end %>
    <% end %>
</div>

app/views/shared/_create_rule.html.erb
<%= simple_form_for @rule  do |f| %>
    <%= f.input :body, label: 'Scrie o regulă nouă' %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, value: 'Regulă nouă', class: 'bck-light neon-green neon-square-button' %>
<% end %>

app/views/shared/_design_shape.html.erb
<div class="design">
    <% 50.times do %>
            <div class="big-circle" style="bottom:<%=rand(10..1000)%>px; left:<%=rand(10..2500)%>px"></div>
    <% end %>
    <% 100.times do %>
            <div class="mid-circle" style="bottom:<%=rand(10..1000)%>px; left:<%=rand(10..2500)%>px"></div>
    <% end %>
    <% 200.times do %>
            <div class="sm-circle" style="bottom:<%=rand(10..1000)%>px; left:<%=rand(10..2500)%>px"></div>
    <% end %>
</div>

<% 20.times do %>
        <div class="big-circle-blue" style="bottom:<%=rand(10..300)%>px; left:<%=rand(10..2500)%>px"></div>
<% end %>
<% 30.times do %>
        <div class="mid-circle-blue" style="bottom:<%=rand(10..300)%>px; left:<%=rand(10..2500)%>px"></div>
<% end %>
<% 100.times do %>
        <div class="sm-circle-blue" style="bottom:<%=rand(10..300)%>px; left:<%=rand(10..2500)%>px"></div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="d-flex align-items-center">
  <div class="container-fluid">
    <div class="row">
      <div class="col d-flex footer-social my-2 justify-content-center">
        <a href="tel:0040745377149" title="Contact telefonic"><i class="fas fa-mobile-alt"></i></a>
        <a href="https://api.whatsapp.com/send?phone=400745377149&text=Bună ziua! Vă rog să-mi spuneți..." title="Contact WhatsApp"><i class="fab fa-whatsapp-square"></i></a>
        <a href="https://www.facebook.com/aquaclub.bacau/" target="_blank" title="Pagina de Facebook"><i class="fab fa-facebook-square"></i></a>
        <a href="https://g.page/aquaclub-bacau?share" target="_blank" title="Traseul până la noi"><i class="fas fa-map-marked-alt"></i></a>
      </div>
      <div class="web-dev position-absolute d-flex flex-column justify-content-around font">
        <p class="m-0">created with ❤️ by</p>
        <p class="m-0 text-center">
          <%= link_to "http://www.ursache.dev" do %>
            <%=  image_tag "dev.png", alt: 'Gabriel Ursache full stack web developer', title: 'Gabriel Ursache full stack web developer' %>
          <% end %>
        </p>
        <p class="m-0">in Bacău - România</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_modal_prices.html.erb
<div class="modal fade" id="prices" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content bck-blue round-border">
        <div class="modal-body font neon-green text-center modal-prices">
          <%= image_tag('undraw_Credit_card_3ed6.svg', id: 'cc-svg') %>
            <p class="prices-bigfont f-w-light-y text-center">Prețuri 2021
            </p>
            <p class='prices-bigfont m-0'><%= image_tag('clock.svg', class: 'mr-3') %></p>
            <p class='prices-bigfont m-0'> zilnic 10:00 - 18:00</p>
            <p class='prices-bigfont m-0'> luni 11:00 - 18:00</p>
            <hr class="bck-neon-green">
            <p class='prices-bigfont m-0'>Luni - Vineri</p>
            <p class='prices-smfont m-0'>25 lei/persoană</p>
            <p class='prices-smfont m-0'>20 lei/copil ( 3 - 14 ani )</p>
            <hr class="bck-neon-green">
            <p class='prices-bigfont m-0'>Sâmbata - Duminica &</p>
            <p class='prices-smfont m-0'>Sărbători legale</p>
            <p class='prices-smfont m-0'>35 lei/persoană</p>
            <p class='prices-smfont m-0'>25 lei/copil > ( 3 - 14 ani )</p>
            <hr class="bck-neon-green">
            <p class='prices-smfont'>Pe perioada în care sunt restricții privind numărul maxim de persoane admise
              în incintă suspendăm toate tipurile de gratuități!
            </p>
            <p class='prices-smfont'>Vă mulțumim pentru înțelegere!</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn font f-w-light bck-blue neon-green" data-dismiss="modal">Am citit!</button>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: 'Aqua Club logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class='pt-2 hover' data-toggle="modal" data-target="#covid-19">
          <i class="fas fa-virus"></i>
        </a>
      </li>
      <li class="nav-item">
        <%= link_to articles_path, class: "nav-link" do %>
          <i class="fas fa-newspaper"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to rules_path, class: "nav-link" do %>
          <i class="fas fa-swimming-pool"></i>
        <% end %>
      </li>
      <li class="nav-item">
        <a class='pt-2 hover' data-toggle="modal" data-target="#prices">
          <i class="fas fa-coins"></i>
        </a>
      </li>
      <li class="nav-item">
        <%= link_to about_path, class: "nav-link" do %>
          <i class="fas fa-info-circle"></i>
        <% end %>
      </li>
    </ul>
  </div>
</div>